version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    mem_limit: 256m
    networks:
      - proxy_app-network

  nextjs-app:
    container_name: nextjs-app-acoating
    build: 
      context: ./nextjs-app
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    volumes:
      - ./nextjs-app:/app
      - /app/node_modules
      - /app/.next
    networks:
      - proxy_app-network
    mem_limit: 768M
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      VIRTUAL_HOST: www.acoating.com, acoating.com
      LETSENCRYPT_HOST: www.acoating.com, acoating.com
      LETSENCRYPT_EMAIL: jason@mavacode.com
    restart: always

  strapi:
    build:
      context: ./strapi-cms
      dockerfile: Dockerfile
    env_file:
    - .env
    container_name: strapi-app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${STRAPI_DATABASE_NAME}
      DATABASE_USERNAME: ${STRAPI_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${STRAPI_DATABASE_PASSWORD}
      DATABASE_HOST: postgres
      DATABASE_PORT: "${DATABASE_PORT:-5432}"
      DATABASE_SSL: "false"
      NODE_ENV: ${NODE_ENV}
      VIRTUAL_HOST: strapi.acoating.com
      LETSENCRYPT_HOST: strapi.acoating.com
      LETSENCRYPT_EMAIL: jason@mavacode.com
    volumes:
      - ./strapi-data:/app/public/uploads  # Persistent volume for uploads
      - ./strapi-config:/app/config  # Persistent volume for configurations
      - ./strapi-api:/app/src/api  # Persistent volume for custom API files
      - ./strapi-components:/app/src/components  # Persistent volume for custom component files
      #- ./strapi-api:/app/src/api  # Dev Mode
      #- ./strapi-extensions:/app/extensions  # Persistent volume for extensions
    ports:
      - "1337:1337"
    restart: always
    mem_limit: 512m
    networks:
      - proxy_app-network

networks:
  proxy_app-network:
    external: true
