version: '3.8'

services:
  nextjs-app:
    container_name: nextjs-app
    build: 
      context: ./nextjs-app
      dockerfile: Dockerfile
    volumes:
      - ./nextjs-app:/app
    networks:
      - proxy_app-network
    mem_limit: 384M
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=yourdomain.com, www.yourdomain.com
      - LETSENCRYPT_HOST=yourdomain.com, www.yourdomain.com
      - LETSENCRYPT_EMAIL=your-email@example.com

  strapi-cms:
    container_name: strapi-cms
    image: strapi/strapi
    command: strapi develop
    volumes:
      - ./strapi-cms:/srv/app
      - /srv/app/node_modules
    networks:
      - proxy_app-network
    mem_limit: 512M
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=${STRAPI_DATABASE_NAME}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=${STRAPI_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${STRAPI_DATABASE_PASSWORD}
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - proxy_app-network
    mem_limit: 128M
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres-data:

networks:
  proxy_app-network:
    external: true
