
// This file was auto-generated by generate-rewrites.mjs. Do not edit manually.
export default {
  async rewrites() {
    return [
  {
    "source": "/1911-gallery",
    "destination": "/1911-gallery.html"
  },
  {
    "source": "/1911-gallery2679",
    "destination": "/1911-gallery2679.html"
  },
  {
    "source": "/1911-gallery4658",
    "destination": "/1911-gallery4658.html"
  },
  {
    "source": "/action-truing",
    "destination": "/action-truing.html"
  },
  {
    "source": "/barrel-chambering",
    "destination": "/barrel-chambering.html"
  },
  {
    "source": "/barrel-crowning",
    "destination": "/barrel-crowning.html"
  },
  {
    "source": "/barrel-threading",
    "destination": "/barrel-threading.html"
  },
  {
    "source": "/bead-blasting",
    "destination": "/bead-blasting.html"
  },
  {
    "source": "/bolt-knob-install",
    "destination": "/bolt-knob-install.html"
  },
  {
    "source": "/camo-gallery",
    "destination": "/camo-gallery.html"
  },
  {
    "source": "/cerakote-colors",
    "destination": "/cerakote-colors.html"
  },
  {
    "source": "/cerakote-firearm-coatings",
    "destination": "/cerakote-firearm-coatings.html"
  },
  {
    "source": "/cerakote-gun-coating-prices",
    "destination": "/cerakote-gun-coating-prices.html"
  },
  {
    "source": "/contest-gallery",
    "destination": "/contest-gallery.html"
  },
  {
    "source": "/faqs",
    "destination": "/faqs.html"
  },
  {
    "source": "/firing-pin-bushing",
    "destination": "/firing-pin-bushing.html"
  },
  {
    "source": "/hunting-gallery",
    "destination": "/hunting-gallery.html"
  },
  {
    "source": "/index",
    "destination": "/index.html"
  },
  {
    "source": "/muzzle-brakes",
    "destination": "/muzzle-brakes.html"
  },
  {
    "source": "/photo-galleries",
    "destination": "/photo-galleries.html"
  },
  {
    "source": "/pillar-bedding",
    "destination": "/pillar-bedding.html"
  },
  {
    "source": "/pistols-gallery",
    "destination": "/pistols-gallery.html"
  },
  {
    "source": "/pistols-gallery4658",
    "destination": "/pistols-gallery4658.html"
  },
  {
    "source": "/revolver-gallery",
    "destination": "/revolver-gallery.html"
  },
  {
    "source": "/scopes-gallery",
    "destination": "/scopes-gallery.html"
  },
  {
    "source": "/services",
    "destination": "/services.html"
  },
  {
    "source": "/side-bolt-release-install",
    "destination": "/side-bolt-release-install.html"
  },
  {
    "source": "/tactical-gallery",
    "destination": "/tactical-gallery.html"
  },
  {
    "source": "/tactical-gallery4658",
    "destination": "/tactical-gallery4658.html"
  },
  {
    "source": "/testimonials",
    "destination": "/testimonials.html"
  },
  {
    "source": "/women-gallery",
    "destination": "/women-gallery.html"
  }
];
  },
};
