name: Deploy to Server

on:
  push:
    branches:
      - main  # Set this to the branch name you use for production releases

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH connection
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to the server
      run: rsync -avz --delete ./ root@24.144.69.20:/root/  # rsync is used here for copying files securely

