name: Deploy to Server and Run Docker Compose

on:
  push:
    branches:
      - main  # or your specific branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH connection
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to the server
      run: rsync -avz -e "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./ root@24.144.69.20:/root/GitHub-delivery/ && ssh -o StrictHostKeyChecking=no root@24.144.69.20 "echo 'Rsync Completed Successfully' &> /root/GitHub-delivery/rsync_log.txt"

    - name: Build and Run Docker Compose with Logging
      run: |
        ssh -o StrictHostKeyChecking=no root@24.144.69.20 "\
          cd /root/ && \
          docker-compose down && \
          docker-compose build >> deployment.log 2>&1 && \
          docker-compose up -d >> deployment.log 2>&1"
      # Redirects both stdout and stderr to deployment.log
 